export const products = [
  {
    id: "1",
    name: "Royal Banarasi Silk Saree",
    price: 45999,
    originalPrice: 52999,
    image: "/elegant-red-banarasi-silk-saree-with-gold-zari-wor.jpg",
    category: "sarees",
    subcategory: "banarasi",
    fabric: "silk",
    occasion: "wedding",
    color: "red",
    rating: 4.8,
    reviews: 124,
    isNew: true,
    isBestseller: true,
  },
  {
    id: "2",
    name: "Kanjivaram Temple Border Saree",
    price: 38999,
    originalPrice: 45999,
    image: "/elegant-purple-kanjivaram-saree-with-temple-border.jpg",
    category: "sarees",
    subcategory: "kanjivaram",
    fabric: "silk",
    occasion: "wedding",
    color: "purple",
    rating: 4.9,
    reviews: 89,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "3",
    name: "Chanderi Cotton Saree",
    price: 8999,
    originalPrice: 11999,
    image: "/elegant-pastel-blue-chanderi-cotton-saree-with-sub.jpg",
    category: "sarees",
    subcategory: "chanderi",
    fabric: "cotton",
    occasion: "casual",
    color: "blue",
    rating: 4.6,
    reviews: 67,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "4",
    name: "Designer Georgette Saree",
    price: 15999,
    originalPrice: 19999,
    image: "/elegant-emerald-green-georgette-saree-with-sequin-.jpg",
    category: "sarees",
    subcategory: "designer",
    fabric: "georgette",
    occasion: "party",
    color: "green",
    rating: 4.7,
    reviews: 156,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "5",
    name: "Men's Silk Kurta Set",
    price: 12999,
    originalPrice: 15999,
    image: "/elegant-cream-silk-kurta-pajama-set-indian-man-wed.jpg",
    category: "kurtas",
    subcategory: "men",
    fabric: "silk",
    occasion: "wedding",
    color: "cream",
    rating: 4.5,
    reviews: 78,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "6",
    name: "Women's Embroidered Kurta",
    price: 5999,
    originalPrice: 7999,
    image: "/elegant-maroon-embroidered-kurta-indian-woman-fest.jpg",
    category: "kurtas",
    subcategory: "women",
    fabric: "cotton",
    occasion: "festive",
    color: "maroon",
    rating: 4.8,
    reviews: 203,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "7",
    name: "Lucknowi Chikankari Kurta",
    price: 8999,
    originalPrice: 10999,
    image: "/elegant-white-lucknowi-chikankari-kurta-indian-wom.jpg",
    category: "kurtas",
    subcategory: "women",
    fabric: "cotton",
    occasion: "casual",
    color: "white",
    rating: 4.7,
    reviews: 145,
    isNew: true,
    isBestseller: true,
  },
  {
    id: "8",
    name: "Paithani Silk Saree",
    price: 55999,
    originalPrice: 65999,
    image: "/elegant-golden-paithani-silk-saree-peacock-motif-i.jpg",
    category: "sarees",
    subcategory: "paithani",
    fabric: "silk",
    occasion: "wedding",
    color: "gold",
    rating: 4.9,
    reviews: 56,
    isNew: false,
    isBestseller: false,
  },
]

export const collections = [
  {
    id: "wedding",
    name: "Wedding Collection",
    description: "Timeless elegance for your special day",
    image: "/indian-bridal-saree-collection-elegant-red-gold.jpg",
    count: 45,
  },
  {
    id: "festive",
    name: "Festive Favorites",
    description: "Celebrate in style",
    image: "/indian-festive-kurta-saree-diwali-collection.jpg",
    count: 68,
  },
  {
    id: "handloom",
    name: "Handloom Heritage",
    description: "Artisan crafted traditions",
    image: "/indian-handloom-saree-weaving-traditional-artisan.jpg",
    count: 32,
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    location: "Mumbai",
    text: "The Banarasi saree I ordered exceeded all expectations. The craftsmanship is impeccable and the delivery was prompt. Vrunda Vihas is now my go-to for ethnic wear.",
    rating: 5,
    image: "/indian-woman-smiling.png",
  },
  {
    id: 2,
    name: "Anjali Patel",
    location: "Ahmedabad",
    text: "I purchased a Kanjivaram for my daughter's wedding. The quality and authenticity of the weave is remarkable. True to the pictures and excellent customer service.",
    rating: 5,
    image: "/indian-woman-elegant-portrait.jpg",
  },
  {
    id: 3,
    name: "Meera Krishnan",
    location: "Chennai",
    text: "Finally found a brand that understands traditional aesthetics with modern sensibilities. The kurtas are comfortable yet elegant. Highly recommend!",
    rating: 5,
    image: "/indian-woman-professional-portrait.png",
  },
]

export const regions = [
  { id: "banarasi", name: "Banarasi", location: "Varanasi" },
  { id: "kanjivaram", name: "Kanjivaram", location: "Tamil Nadu" },
  { id: "chanderi", name: "Chanderi", location: "Madhya Pradesh" },
  { id: "paithani", name: "Paithani", location: "Maharashtra" },
  { id: "bandhani", name: "Bandhani", location: "Gujarat" },
  { id: "patola", name: "Patola", location: "Gujarat" },
]

export const fabrics = ["Silk", "Cotton", "Georgette", "Chiffon", "Linen", "Organza"]
export const occasions = ["Wedding", "Festive", "Casual", "Party", "Office"]

export const productDetails = {
  "1": {
    id: "1",
    name: "Royal Banarasi Silk Saree",
    price: 45999,
    originalPrice: 52999,
    images: [
      "/placeholder.svg?key=ib1ry",
      "/placeholder.svg?key=z4w1r",
      "/placeholder.svg?key=dfutu",
      "/placeholder.svg?key=9pob9",
    ],
    category: "sarees",
    subcategory: "banarasi",
    fabric: "Pure Banarasi Silk",
    occasion: "wedding",
    color: "Red with Gold Zari",
    rating: 4.8,
    reviews: 124,
    isNew: true,
    isBestseller: true,
    description:
      "Experience the epitome of Indian craftsmanship with this exquisite Royal Banarasi Silk Saree. Handwoven by master artisans in Varanasi, this saree features intricate gold zari work with traditional motifs that have been passed down through generations.",
    features: [
      "Handwoven by master artisans in Varanasi",
      "Pure Banarasi silk with real gold zari",
      "Traditional buta and jaal work throughout",
      "Intricately designed pallu with temple border",
      "Comes with matching unstitched blouse piece",
    ],
    specifications: {
      "Saree Length": "5.5 meters",
      "Blouse Piece": "0.8 meters (unstitched)",
      Weight: "650 grams (approx)",
      "Wash Care": "Dry clean only",
      "Weave Type": "Handloom",
      "Zari Type": "Real Gold Zari",
      Origin: "Varanasi, Uttar Pradesh",
    },
    sizes: ["Free Size"],
    blouseOptions: [
      { id: "unstitched", name: "Unstitched", price: 0 },
      { id: "ready-34", name: "Ready to Wear (34)", price: 1500 },
      { id: "ready-36", name: "Ready to Wear (36)", price: 1500 },
      { id: "ready-38", name: "Ready to Wear (38)", price: 1500 },
      { id: "ready-40", name: "Ready to Wear (40)", price: 1500 },
      { id: "custom", name: "Custom Stitched", price: 2500 },
    ],
    inStock: true,
    deliveryEstimate: "5-7 business days",
  },
  "2": {
    id: "2",
    name: "Kanjivaram Temple Border Saree",
    price: 38999,
    originalPrice: 45999,
    images: [
      "/placeholder.svg?key=wgpyu",
      "/placeholder.svg?key=rlgfl",
      "/placeholder.svg?key=5f0ld",
      "/placeholder.svg?key=vhh57",
    ],
    category: "sarees",
    subcategory: "kanjivaram",
    fabric: "Pure Kanjivaram Silk",
    occasion: "wedding",
    color: "Purple with Gold",
    rating: 4.9,
    reviews: 89,
    isNew: false,
    isBestseller: true,
    description:
      "A masterpiece from the looms of Kanchipuram, this Kanjivaram saree embodies centuries of weaving tradition. The majestic temple border and rich purple hue make it perfect for bridal trousseaus and auspicious occasions.",
    features: [
      "Authentic Kanjivaram silk from Tamil Nadu",
      "Traditional temple border design",
      "Contrast pallu with intricate peacock motifs",
      "Pure mulberry silk with zari work",
      "GI certified authentic weave",
    ],
    specifications: {
      "Saree Length": "5.5 meters",
      "Blouse Piece": "0.8 meters (unstitched)",
      Weight: "700 grams (approx)",
      "Wash Care": "Dry clean only",
      "Weave Type": "Handloom",
      "Zari Type": "Pure Zari",
      Origin: "Kanchipuram, Tamil Nadu",
    },
    sizes: ["Free Size"],
    blouseOptions: [
      { id: "unstitched", name: "Unstitched", price: 0 },
      { id: "ready-34", name: "Ready to Wear (34)", price: 1500 },
      { id: "ready-36", name: "Ready to Wear (36)", price: 1500 },
      { id: "ready-38", name: "Ready to Wear (38)", price: 1500 },
      { id: "ready-40", name: "Ready to Wear (40)", price: 1500 },
      { id: "custom", name: "Custom Stitched", price: 2500 },
    ],
    inStock: true,
    deliveryEstimate: "5-7 business days",
  },
}

export const productReviews = [
  {
    id: 1,
    productId: "1",
    author: "Priya Sharma",
    location: "Mumbai",
    rating: 5,
    date: "2024-11-15",
    title: "Absolutely stunning!",
    content:
      "The saree exceeded all my expectations. The zari work is exquisite and the fabric quality is exceptional. Wore it for my sister's wedding and received so many compliments!",
    verified: true,
    helpful: 24,
    images: [],
  },
  {
    id: 2,
    productId: "1",
    author: "Meera Krishnan",
    location: "Chennai",
    rating: 5,
    date: "2024-11-10",
    title: "Worth every penny",
    content:
      "This is my third purchase from Vrunda Vihas and they never disappoint. The Banarasi is authentic and the colors are exactly as shown. Delivery was also prompt.",
    verified: true,
    helpful: 18,
    images: [],
  },
  {
    id: 3,
    productId: "1",
    author: "Anjali Gupta",
    location: "Delhi",
    rating: 4,
    date: "2024-11-05",
    title: "Beautiful but heavy",
    content:
      "The saree is gorgeous and perfect for special occasions. Only reason for 4 stars is that it's quite heavy, which is expected for pure Banarasi but something to consider.",
    verified: true,
    helpful: 12,
    images: [],
  },
]
